'use strict';
/**
 * The full catalogue: every Q / R / Z entry from "OA Master Plan.md".
 *
 * Generated by  node tools/build_catalog.js  so the portal can never drift
 * out of sync with the plan document. Re-run that after editing the doc.
 *
 * Seven questions are `playable` - they have a full statement, hidden tests
 * and a judge here. The rest are catalogued: platform questions link out,
 * modelled ones show their statement from the plan so you can still solve
 * them locally, and Z entries are the aptitude set.
 */
const fs = require('node:fs');
const path = require('node:path');

const GENERATED = path.join(__dirname, 'catalog.generated.json');

/** Exact links for the Week-1 platform problems, verified by hand. */
const VERIFIED_URLS = {
  Q1: 'https://leetcode.com/problems/longest-consecutive-sequence/',
  Q5: 'https://leetcode.com/problems/contains-duplicate-ii/',
  Q6: 'https://leetcode.com/problems/subarray-sum-equals-k/',
  Q7: 'https://leetcode.com/problems/subarray-sums-divisible-by-k/',
  Q8: 'https://leetcode.com/problems/continuous-subarray-sum/',
  Q9: 'https://leetcode.com/problems/maximum-size-subarray-sum-equals-k/',
  Q10: 'https://cses.fi/problemset/task/1662',
  Q13: 'https://leetcode.com/problems/corporate-flight-bookings/',
  Q14: 'https://leetcode.com/problems/product-of-array-except-self/',
  Q15: 'https://leetcode.com/problems/check-if-all-1s-are-at-least-length-k-places-away/',
  Q16: 'https://cses.fi/problemset/task/1164',
  Q19: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
  Q20: 'https://leetcode.com/problems/max-consecutive-ones-iii/',
  Q21: 'https://leetcode.com/problems/longest-repeating-character-replacement/',
  Q22: 'https://leetcode.com/problems/sliding-window-maximum/',
};

let CATALOG = [];

if (fs.existsSync(GENERATED)) {
  CATALOG = JSON.parse(fs.readFileSync(GENERATED, 'utf8'));
  for (const c of CATALOG) {
    if (VERIFIED_URLS[c.docId]) { c.url = VERIFIED_URLS[c.docId]; c.urlExact = true; }
  }
} else {
  console.warn('\n  catalog.generated.json missing - run: node tools/build_catalog.js\n');
}

module.exports = { CATALOG };
